version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - trading_system_net

  market_analysis:
    build: ../market-analysis
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      - ../market-analysis:/app
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - trading_system_net

networks:
  trading_system_net:
    driver: bridge

volumes:
  frontend_node_modules:
  frontend_next_cache:
