services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_FRONTEND_SERVICE}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - HOST=${API_HOST}
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_TRADE_MANAGER_SERVICE=${DOCKER_TRADE_MANAGER_SERVICE}
      - DOCKER_MARKET_ANALYSIS_SERVICE=${DOCKER_MARKET_ANALYSIS_SERVICE}
      - DOCKER_TRADE_DISCOVERY_SERVICE=${DOCKER_TRADE_DISCOVERY_SERVICE}
      - API_BASE_URL=${API_BASE_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST}
    command: npm run dev -- -H ${API_HOST}
    networks:
      - trading_system_net

  market_analysis:
    build: ${MARKET_ANALYSIS_PATH}
    container_name: ${DOCKER_MARKET_ANALYSIS_SERVICE}
    ports:
      - "${MARKET_ANALYSIS_PORT}:${MARKET_ANALYSIS_PORT}"
    environment:
      - API_PORT=${MARKET_ANALYSIS_PORT}
      - API_HOST=${API_HOST}
      - PYTHONPATH=${PYTHONPATH}
    volumes:
      - ${MARKET_ANALYSIS_PATH}:/app
    command: uvicorn src.api.app:app --host ${API_HOST} --port ${MARKET_ANALYSIS_PORT} --reload
    networks:
      - trading_system_net

  trade_manager:
    container_name: ${DOCKER_TRADE_MANAGER_SERVICE}
    build: ${TRADE_MANAGER_PATH}
    ports:
      - "${TRADE_MANAGER_PORT}:${TRADE_MANAGER_PORT}"
    environment:
      - API_PORT=${TRADE_MANAGER_PORT}
      - API_HOST=${API_HOST}
      - PYTHONPATH=${PYTHONPATH}
    volumes:
      - ${TRADE_MANAGER_PATH}:/app
    command: uvicorn src.api.main:app --host ${API_HOST} --port ${TRADE_MANAGER_PORT} --reload
    networks:
      - trading_system_net

  trade_discovery:
    container_name: ${DOCKER_TRADE_DISCOVERY_SERVICE}
    build: ${TRADE_DISCOVERY_PATH}
    ports:
      - "${TRADE_DISCOVERY_PORT}:${TRADE_DISCOVERY_PORT}"
    environment:
      - API_PORT=${TRADE_DISCOVERY_PORT}
      - API_HOST=${API_HOST}
      - PYTHONPATH=${PYTHONPATH}
    volumes:
      - ${TRADE_DISCOVERY_PATH}:/app
    command: uvicorn src.api.app:app --host ${API_HOST} --port ${TRADE_DISCOVERY_PORT} --reload
    networks:
      - trading_system_net

  prometheus:
    image: prom/prometheus:latest
    container_name: ${DOCKER_PROMETHEUS_SERVICE}
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - trading_system_net

  grafana:
    image: grafana/grafana:latest
    container_name: ${DOCKER_GRAFANA_SERVICE}
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - trading_system_net

networks:
  trading_system_net:
    name: ${DOCKER_NETWORK_NAME}
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: